apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaweb
  template:
    metadata:
      labels:
        app: javaweb
    spec:
      containers:
      - name: javacont
        image: dockerakashde/image:tags
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javasvc
spec:
  type: NodePort
  selector:
    app: javaweb
  ports:
  - name: http
    port: 80
    targetPort: 8080
