apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaweb
  template:
    metadata:
      labels:
        app: javaweb
    spec:
      containers:
      - name: javacont
        image: dockerhakashde/maven-web-app:tags
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: javasvc
spec:
  type: NodePort
  selector:
    app: javaweb
  ports:
  - name: http
    port: 80
    targetPort: 8080
